# Data Cleaning and Processing

## Plan
1. Loading the London data from London datastore
   a. the well-being data can be found here: https://data.london.gov.uk/dataset/london-ward-well-being-scores
   include data of 2009 to 2013: subjective well-being score, public transport accessibility scores, crime rate, deliberate       fires, life expectancy, childhood obesity, incapacity benefits claimant rate, unemployment rate, unauthorised pupil
   absence, children in out-of-work households, GCSE point scores.
   b. the population density of wards can be found here: https://data.london.gov.uk/dataset/land-area-and-population-density-
   ward-and-borough
   c. the travel by bicycle data of wards can be found here: https://data.london.gov.uk/dataset/travel-work-bicycle-ward
2. removing uneccessary columns, removing outliers and NAN value, transform data type, calculate average value
3. test multicollinearity using VIF, remove variables with high multicollinearity.

In [1]:
# Load libraries
import pandas as pd
import os
import re
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import scipy.stats
import statsmodels.api as sm
from statsmodels.tools.tools import add_constant
from sklearn.preprocessing import StandardScaler
from scipy import stats

from statsmodels.stats.outliers_influence import variance_inflation_factor 
import imageio

## Initial data wrangling
Loading in the Data and remove unnecessary columns.
For the data, we have already make some simple adjustments in previous. Please see the data file.

In [2]:
# open data files
df_wellbeing = pd.read_csv("https://raw.githubusercontent.com/songzimen/London_subjective-well-being_model/main/data/london-ward-well-being-probability-scores.csv")
df_pdensity = pd.read_csv('https://raw.githubusercontent.com/songzimen/London_subjective-well-being_model/main/data/housing-density-ward.csv')
df_accessnature = pd.read_csv('https://raw.githubusercontent.com/songzimen/London_subjective-well-being_model/main/data/public-open-space-nature-ward_access-to-nature.csv')
df_bicycle = pd.read_csv('https://raw.githubusercontent.com/songzimen/London_subjective-well-being_model/main/data/travel-work-bicycle-census-2001-2011-ward.csv')

In [3]:
# Define the columns to calculate the average for each element
elements = {
    "Childhood Obesity": ["Childhood Obesity 2009", "Childhood Obesity 2010", "Childhood Obesity 2011", "Childhood Obesity 2012", "Childhood Obesity 2013"],
    "Incapacity Benefit rate": ["Incapacity Benefit rate - 2009", "Incapacity Benefit rate - 2010", "Incapacity Benefit rate - 2011", "Incapacity Benefit rate - 2012", "Incapacity Benefit rate - 2013"],
    "Unemployment rate": ["Unemployment rate 2009", "Unemployment rate 2010", "Unemployment rate 2011", "Unemployment rate 2012", "Unemployment rate 2013"],
    "Crime rate": ["Crime rate - 2009", "Crime rate - 2010", "Crime rate - 2011", "Crime rate - 2012", "Crime rate - 2013"],
    "Deliberate Fires": ["Deliberate Fires - 2009", "Deliberate Fires - 2010", "Deliberate Fires - 2011", "Deliberate Fires - 2012", "Deliberate Fires - 2013"],
    "GCSE point scores": ["GCSE point scores - 2009", "GCSE point scores - 2010", "GCSE point scores - 2011", "GCSE point scores - 2012", "GCSE point scores - 2013"],
    "Unauthorised Absence in All Schools (%)": ["Unauthorised Absence in All Schools (%) - 2009", "Unauthorised Absence in All Schools (%) - 2010", "Unauthorised Absence in All Schools (%) - 2011", "Unauthorised Absence in All Schools (%) - 2012", "Unauthorised Absence in All Schools (%) - 2013"],
    "% dependent children in out-of-work households": ["% dependent children in out-of-work households - 2009", "% dependent children in out-of-work households - 2010", "% dependent children in out-of-work households - 2011", "% dependent children in out-of-work households - 2012", "% dependent children in out-of-work households - 2013"],
    "Public Transport Accessibility": ["Public Transport Accessibility - 2009", "Public Transport Accessibility - 2010", "Public Transport Accessibility - 2011", "Public Transport Accessibility - 2012", "Public Transport Accessibility - 2013"],
    "Subjective well-being average score": ["Subjective well-being average score, 2011/12 and 2012/13", "Subjective well-being average score, 2011/12 and 2012/13.1", "Subjective well-being average score, 2011/12 and 2012/13.2", "Subjective well-being average score, 2011/12 and 2012/13.3", "Subjective well-being average score, 2013"]
}

# Convert all columns to numeric, setting errors='coerce' to turn non-numeric values to NaN
for element_columns in elements.values():
    for column in element_columns:
        df_wellbeing[column] = pd.to_numeric(df_wellbeing[column], errors='coerce')

# Recalculate the averages and simultaneously drop the old columns
for element_name, element_columns in elements.items():
    df_wellbeing[element_name + " Average"] = df_wellbeing[element_columns].mean(axis=1)
    # Drop the old columns after calculating the average
    df_wellbeing.drop(columns=element_columns, inplace=True)

df_wellbeing.drop(columns=['Old Ward Code', 'Borough', 'Life Expectancy 2005-2009', 
                           'Life Expectancy 2006-2010', 'Life Expectancy 2007-11', 'Life Expectancy 2008-12',
                          'Homes with access to open space & nature, and % greenspace - 2009', 
                           'Homes with access to open space & nature, and % greenspace - 2010',
                          'Homes with access to open space & nature, and % greenspace - 2011',
                          'Homes with access to open space & nature, and % greenspace - 2012',
                          'Homes with access to open space & nature, and % greenspace - 2013'], inplace=True)


# Display the first few rows of the dataset with new columns
df_wellbeing = df_wellbeing[0:625]
df_wellbeing.head()

,New ward code,Ward,Life Expectancy 2009-13,Childhood Obesity Average,Incapacity Benefit rate Average,Unemployment rate Average,Crime rate Average,Deliberate Fires Average,GCSE point scores Average,Unauthorised Absence in All Schools (%) Average,% dependent children in out-of-work households Average,Public Transport Accessibility Average,Subjective well-being average score Average
0,E09000001,City of London,86.4,24.18,2.04,2.40,16.28,0.38,353.8,0.544,12.8,7.72,7.62
1,E05000026,Abbey,82.0,21.96,3.18,8.50,152.42,1.14,328.4,1.412,29.8,5.92,7.88
2,E05000027,Alibon,79.0,25.90,5.40,9.86,112.92,0.80,324.8,1.430,35.2,3.24,7.44
3,E05000028,Becontree,79.2,24.10,5.10,9.72,126.00,0.86,328.0,1.496,34.0,2.86,7.60
4,E05000029,Chadwell Heath,80.8,25.20,5.02,8.50,115.74,2.22,329.8,1.572,31.8,2.28,7.20

In [4]:
## wrangling the population density data
# only keep the 2011 population density data of wards
df_pdensity = df_pdensity[0:624]

## wrangling the data of homes with good access to nature
df_accessnature = df_accessnature[0:625]

## wrangling the data of travel work bicycle
df_bicycle = df_bicycle[0:625]

In [5]:
# merge other variables into df_wellbeing
# standerdize the ward code columns name
df_wellbeing.rename(columns={'New ward code':'ward_code'}, inplace=True)
df_pdensity.rename(columns={'Code':'ward_code'}, inplace=True)
df_accessnature.rename(columns={'Ward':'ward_code'}, inplace=True)
df_bicycle.rename(columns={'Ward':'ward_code'}, inplace=True)

df=pd.merge(df_wellbeing, df_pdensity[['ward_code', 'Population_per_hectare']], on='ward_code', how='left')
df.rename(columns={'Population_per_hectare':'population_per_hectare'}, inplace=True)
# we find online that the population_per_hectare of citi of london is 25.52, so we mannually input it.
df.loc[0, 'population_per_hectare'] = 25.52

df=pd.merge(df, df_accessnature[['ward_code', '% homes with good access to nature']], on='ward_code', how='left')
df.rename(columns={'% homes with good access to nature':'homes_good_access_nature'}, inplace=True)
df['homes_good_access_nature']=df['homes_good_access_nature'].astype(float)

df=pd.merge(df, df_bicycle[['ward_code', '2011;% travel by bicycle']], on='ward_code', how='left')
df.rename(columns={'2011;% travel by bicycle':'travel_work_bicycle'}, inplace=True)

# move Subjective well-being average score Average to end
column = df.pop('Subjective well-being average score Average')
df['Subjective well-being average score Average'] = column

In [6]:
print(df.dtypes)

ward_code                                                  object
Ward                                                       object
Life Expectancy 2009-13                                   float64
Childhood Obesity Average                                 float64
Incapacity Benefit rate Average                           float64
Unemployment rate Average                                 float64
Crime rate Average                                        float64
Deliberate Fires Average                                  float64
GCSE point scores Average                                 float64
Unauthorised Absence in All Schools (%) Average           float64
% dependent children in out-of-work households Average    float64
Public Transport Accessibility Average                    float64
population_per_hectare                                    float64
homes_good_access_nature                                  float64
travel_work_bicycle                                       float64
Subjective well-being average score Average               float64
dtype: object

## Using VIF to filter variables

In [7]:
def drop_column_using_vif_(df, thresh=5):
    '''
    This function is adjusted from: https://stackoverflow.com/a/51329496/4667568

    Calculates VIF each feature in a pandas dataframe, and repeatedly drop the columns with the highest VIF
    A constant must be added to variance_inflation_factor or the results will be incorrect

    :param df: the pandas dataframe containing only the predictor features, not the response variable
    :param thresh: (default 5) the threshould VIF value. If the VIF of a variable is greater than thresh, it should be removed from the dataframe
    :return: dataframe with multicollinear features removed
    '''
    vif_history = []  # save the list for VIFs of each iteration

    while True:
        
        # adding a constatnt item to the data. add_constant is a function from statsmodels (see the import above)
        df_with_const = add_constant(df,has_constant='add')

        if 'const' in df_with_const.columns:
            vif_df = pd.Series([variance_inflation_factor(df_with_const.values, i) for i in range(df_with_const.shape[1])], name= "VIF", 
                                index=df_with_const.columns).to_frame()

            # drop the const
            vif_df = vif_df.drop('const')
            vif_history.append(vif_df.copy()) 
        else:
            raise ValueError("constant column 'const' not successfully added")
        
        # if the largest VIF is above the thresh, remove a variable with the largest VIF
        # If there are multiple variabels with VIF>thresh, only one of them is removed. This is because we want to keep as many variables as possible
        if vif_df.VIF.max() > thresh:
            # If there are multiple variables with the maximum VIF, choose the first one
            index_to_drop = vif_df.index[vif_df.VIF == vif_df.VIF.max()].tolist()[0]
            print('Dropping: {} (VIF: {})'.format(index_to_drop, vif_df.loc[index_to_drop, 'VIF']))
            df = df.drop(columns = index_to_drop)
        else:
            # No VIF is above threshold. Exit the loop
            break

    return df, vif_history

def show_vif_values(df, dependent_variable):
    """
    Takes a dataframe and the name of the dependent variable, 
    and returns a dataframe with the VIF values for each column (independent variables).
    """
    # Exclude the dependent_variable column from the analysis
    df.drop(columns=dependent_variable, inplace=True)

    df_with_const = add_constant(df,has_constant='add')

    vif_df = pd.Series([variance_inflation_factor(df_with_const.values, i) for i in range(df_with_const.shape[1])], name= "VIF", 
                            index=df_with_const.columns).to_frame()

    vif_df = vif_df.drop('const')

    # Sort the dataframe by VIF values in descending order
    vif_df = vif_df.sort_values(by='VIF', ascending=False)

    return vif_df

In [8]:
df_VIF, VIF_history = drop_column_using_vif_(df.drop(['Subjective well-being average score Average','ward_code','Ward'], axis=1), thresh=4)

Dropping: % dependent children in out-of-work households Average (VIF: 9.701918780144423)

In [9]:
df=df.drop(['% dependent children in out-of-work households Average'], axis=1)
df.to_csv('data/data_clean.csv', index=False)

In [10]:
# standardized data
# choose columns
columns_to_scale = df.columns.drop(['ward_code', 'Ward'])

# initial standardized method
scaler = StandardScaler()

# standardized data
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])


print(df.head())

   ward_code            Ward  Life Expectancy 2009-13  \
0  E09000001  City of London                 1.942606
1  E05000026           Abbey                -0.002476
2  E05000027          Alibon                -1.328668
3  E05000028       Becontree                -1.240255
4  E05000029  Chadwell Heath                -0.532952

   Childhood Obesity Average  Incapacity Benefit rate Average  \
0                   0.607412                        -1.137448
1                   0.143676                        -0.330374
2                   0.966703                         1.241298
3                   0.590701                         1.028910
4                   0.820480                         0.972273

   Unemployment rate Average  Crime rate Average  Deliberate Fires Average  \
0                  -1.136770           -2.391886                 -0.545340
1                   0.798817            1.754579                  0.777489
2                   1.230358            0.551513                  0.185697
3                   1.185935            0.949895                  0.290131
4                   0.798817            0.637403                  2.657298

   GCSE point scores Average  Unauthorised Absence in All Schools (%) Average  \
0                   0.661178                                        -1.467995
1                  -0.823559                                         0.912848
2                  -1.033995                                         0.962220
3                  -0.846941                                         1.143252
4                  -0.741723                                         1.351713

   Public Transport Accessibility Average  population_per_hectare  \
0                                2.973516               -1.160699
1                                1.646085                0.434914
2                               -0.330312               -0.072686
3                               -0.610547                0.217864
4                               -1.038275               -1.068488

   homes_good_access_nature  travel_work_bicycle  \
0                 -2.454556             0.411746
1                  0.778943            -0.921628
2                 -1.530699            -0.862367
3                  0.284020            -0.684584
4                 -1.266740            -0.803106

   Subjective well-being average score Average
0                                    -0.078171
1                                     0.860001
2                                    -0.727675
3                                    -0.150338
4                                    -1.593680

In [11]:
df.to_csv('data/data_clean_standardized.csv', index=False)